import { Field } from '@/components/ui/field';
import { Input } from '@/components/ui/input';

interface TotpSetupProps {
  /** Pre-rendered inline SVG from `qrSvg()`. */
  svg: string;
  /** Base32, for anyone whose camera cannot see the screen. */
  setupKey: string;
}

/**
 * The scan-and-confirm panel, shared by first enrolment and re-scanning onto a
 * new phone.
 *
 * The setup key is shown alongside the QR rather than behind a disclosure. A
 * camera fails often enough — a desktop with no webcam, a locked-down work
 * phone, a screenshot pasted into chat — that hiding the fallback just means
 * someone gets stuck. It is the same secret either way.
 */
export function TotpSetup({ svg, setupKey }: TotpSetupProps) {
  return (
    <>
      <div className="mt-5 flex justify-center rounded-lg border border-border bg-white p-3">
        {/*
          The QR is a server-rendered SVG string, inlined rather than given an
          image src: the URI it encodes contains the shared secret, and a
          secret in a URL reaches the access log, the history and the referrer.
        */}
        <div
          role="img"
          aria-label="QR code for your authenticator app"
          // Safe here and only here: `svg` is generated by `qrcode` from a URI
          // we built ourselves. No user input reaches it.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      </div>

      <div className="mt-4">
        <p className="text-[13px] text-muted-foreground">
          Can&rsquo;t scan? Add the account by hand with this key:
        </p>
        <p className="numeric mt-1.5 break-all rounded-md border border-border bg-surface px-3 py-2 font-mono text-[13px]">
          {setupKey}
        </p>
        <p className="mt-1.5 text-[13px] text-muted-foreground">
          Time-based, SHA1, 6 digits, 30 seconds — the defaults in every
          authenticator app.
        </p>
      </div>

      <Field
        id="code"
        label="Enter the 6-digit code to confirm"
        help="This proves the code reached your phone before we rely on it."
        required
      >
        {(props) => (
          <Input
            {...props}
            name="code"
            type="text"
            inputMode="numeric"
            autoComplete="one-time-code"
            pattern="\d{6}"
            maxLength={6}
            required
            className="font-mono tracking-[0.3em]"
          />
        )}
      </Field>
    </>
  );
}
