import { OWNER } from '@/lib/storage/object-key';

/**
 * Where an invoice or receipt PDF lives in the private bucket.
 *
 * The layout is the one docs/ENVIRONMENT.md §3 already specified —
 * `company/invoices/{fiscal_year}/{invoice_no}.pdf` — with one addition: a
 * short fingerprint of the rendered HTML before the extension.
 *
 * **The fingerprint is what makes the cache safe, and it is not an
 * optimisation.** An invoice is not a frozen document the way a receipt is.
 * Its badge changes from UNPAID to PAID, its balance due falls, `past_due`
 * appears when the clock passes the due date — all correctly, all after the
 * number was allocated. A PDF stored under the bare invoice number would
 * therefore be served for months saying UNPAID about an invoice that was paid
 * in March.
 *
 * Content-addressing removes the problem rather than managing it. The key is
 * derived from the exact bytes that would be printed, so a document that has
 * changed simply misses and is rendered again. There is no invalidation step
 * to forget, no TTL to tune, and no state in which a stale document can be
 * served — the failure mode of a cache on a financial document is a customer
 * holding a PDF that contradicts their account, and that mode does not exist
 * here.
 *
 * Superseded renders stay in the bucket. That is wanted: they are what the
 * invoice looked like when it was sent, which is the question an argument
 * about a payment actually turns on. A handful of 150 KB objects per invoice
 * is not a storage problem worth solving with a delete.
 *
 * Pure string work and no `server-only`, like its public-bucket sibling: this
 * is the last thing between a document number and a bucket path, so it is
 * tested directly.
 */

export const INVOICE_PDF_PREFIX = `${OWNER}/invoices`;
export const RECEIPT_PDF_PREFIX = `${OWNER}/receipts`;

/** Long enough that a collision is not a thing that happens. */
export const FINGERPRINT_LENGTH = 16;

export interface DocumentKeyInput {
  kind: 'invoice' | 'receipt';
  /** `INV-2083/84-000012` or `TXN-2083/84-00000008`. */
  number: string;
  /** `2083/84`. */
  fiscalYear: string;
  /** Lowercase hex, `FINGERPRINT_LENGTH` characters. */
  fingerprint: string;
}

export function documentPdfKey({
  kind,
  number,
  fiscalYear,
  fingerprint,
}: DocumentKeyInput): string {
  const prefix = kind === 'invoice' ? INVOICE_PDF_PREFIX : RECEIPT_PDF_PREFIX;

  return (
    `${prefix}/${segment(fiscalYear, 'fiscal year')}` +
    `/${segment(number, 'document number')}-${hex(fingerprint)}.pdf`
  );
}

/**
 * One path segment from a document number or a fiscal year.
 *
 * Both contain a slash — `INV-2083/84-000012` is one identifier and
 * `2083/84` is one year — and a slash in a key is a directory. It becomes a
 * dash, which is the same substitution the download filenames already make.
 *
 * **Anything else throws rather than being scrubbed.** These values are
 * generated by `packages/accounting/numbering.ts` and cannot legitimately
 * contain anything but digits, letters, dashes and that one slash. A value
 * that does is a bug somewhere upstream, and quietly reducing it to something
 * key-shaped would write a real document to a wrong-but-plausible path — the
 * kind of thing that is only noticed when someone goes looking for an invoice
 * and it is not where it should be.
 */
function segment(value: string, what: string): string {
  if (!/^[A-Za-z0-9][A-Za-z0-9/_.-]*$/.test(value) || value.includes('..')) {
    throw new Error(
      `Unusable ${what} for an object key: ${JSON.stringify(value)}`,
    );
  }

  return value.replace(/\//g, '-');
}

function hex(fingerprint: string): string {
  if (!new RegExp(`^[0-9a-f]{${FINGERPRINT_LENGTH}}$`).test(fingerprint)) {
    throw new Error(`Fingerprint is not ${FINGERPRINT_LENGTH} hex characters`);
  }

  return fingerprint;
}
